### ISSUE TITLE
Not working (At least on iOS 12)

### ISSUE THREAD

**Issue by kodyrouse** [mgatto/cordova-plugin-lifecycle-events-extra#1]
**Environment**
iPhone 6 Plus
iOS 12

**Steps Taken**
- Added plugin to project (you also wrote Cordova plugin install and it's plugin add :))
- Copy and pasted event listener with timeOut AFTER DeviceReady event fires

**Results**
Unable to log nor send Ajax data both inside and outside of the timeOut (only two operations I attempted)

**Comment by kodyrouse** [comment]
I noticed I did not see CordovaPluginLifecycleEventsExtra.m nor CordovaPluginLifecycleEventsExtra.h in my plugins folder in XCode. If I copy and pasted the code you wrote into another plugin (wanted to check if it was an issue with registering the plugin) it logs correctly in the Xcode console but the "will terminate" event never fires inside my app

**Comment by mgatto** [comment]
Hello,

I had a similar issue with the Objective-C files not showing in XCode. I'm not sure why. It went away after I cleaned out my platform and plugins with https://www.npmjs.com/package/cordova-clean .

I fixed the doc error; thanks!

I haven't tested on ios12 and won't be able to until November when we upgrade XCode.

I'll give this a closer look; can you post your JS event listener?

**Comment by kodyrouse** [comment]
Here it is:

    document.addEventListener("willterminate", function() {

		setTimeout(function() {

			console.log("Terminating");

			var sendDataJSON = {
				action: "updateAfterTerminate"
			}

			createBackendRequest(sendDataJSON, function() {
				// Do nothing yet
		    });
        }, 0);
    });

Does the plugin work for you? I wonder if the cordova container is destroyed immediately without warning, hence why the event listener never fires. I'm not sure though. I know you have about 5 seconds after termination to do stuff for iOS --> [https://stackoverflow.com/questions/34578044/how-much-time-do-i-have-after-applicationwillterminate-invoked](url)

**Comment by mgatto** [comment]
It does work for me. Two things I can think of now. I assume you have your code above within the deviceready listener. The second, more important one is this unfortunate condition I discovered yesterday: The underlying ios event is only called if the app is up-swiped from the multi-tasking screen if the app is _not_ backgrounded. 

Apple has this to say:

"Suspended apps receive no notification when they are terminated; the system kills the process and reclaims the corresponding memory. If an app is currently running in the background and not suspended, the system calls the applicationWillTerminate: of its app delegate prior to termination. The system does not call this method when the device reboots.

In addition to the system terminating your app, the user can terminate your app explicitly using the multitasking UI. User-initiated termination has the same effect as terminating a suspended app. The app’s process is killed and no notification is sent to the app."

Unfortunately, it looks as if this custom event handler has limited usefulness for our use cases :-(

**Comment by kodyrouse** [comment]
Sorry for that late response :) I was already aware that applicationWillTerminate will only fire if it's never been suspended (i.e. the user double clicks the home button and swipes up). That's the exact use case I'm using but it still isn't working :/ and that is correct - I do have the posted code inside my deviceReady method
